model_version: v6_smooth
model_name: residual_sr
scale: 2
num_res_blocks: 24
channels: 192

patch_size: 192
batch_size: 32
epochs: 200
learning_rate: 0.0001

mixed_precision: true
num_workers: 2

# Loss config
use_perceptual_loss: true
perceptual_weight: 0.01
